Repository Perfitt-11-supreme/11-supreme, pull requests merged in 2024-10, with the labels that each got.

#180 deploy: Create node.js.yml
  .github/workflows/node.js.yml
Labels: deploy🚀

#181 deploy: Update node.js.yml
  .github/workflows/node.js.yml
Labels: deploy🚀

#182 deploy: Update node.js.yml
  .github/workflows/node.js.yml
Labels: deploy🚀

#185 deploy: envproduction 추가, 이그노어 추가
  .gitignore
Labels: deploy🚀

#186 Refactor 성능개선 im
  index.html
  package.json
  public/robots.txt
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/emptyshoesroom.css.ts
  src/components/empty-shoes-room/header/Header.tsx
  src/components/empty-shoes-room/header/header.css.ts
  src/components/kebab/Kebab.tsx
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-info/shoes-info.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/shoes-registry/star-rating/starrating.css.ts
  src/components/slider/Slider.tsx
  src/components/slider/slider.css.ts
  src/index.css.ts
  src/router/index.tsx
  src/types/shoesroom.d.ts
  tsconfig.app.tsbuildinfo
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: refactor♻️

#187 Feat liked, viewed page
  src/components/mypage/liked-and-viewed-history-button/likedAndViewedHistoryButton.css.ts
  src/components/mypage/liked-in-brand/LikedInBrand.tsx
  src/components/mypage/liked-in-brand/likedInBrand.css.ts
  src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
  src/components/mypage/size-recommendation-card/sizeRecommendationCard.css.ts
  src/components/sidemenu/sidemenuMypageLinks.css.ts
  src/firebase/firebase.ts
  src/hooks/useAddUserIdToFirestoreHook.ts
  src/pages/liked-page/LikedPage.tsx
  src/pages/liked-page/likedPage.css.ts
  src/pages/viewed-history-page/ViewedHistoryPage.tsx
  src/pages/viewed-history-page/viewedHistoryPage.css.ts
  src/stores/useLikedStore.ts
  src/stores/useViewedHistoryStore.ts
Labels: style💄, feat✨, fix🐛, chore 🩹

#192 chore: 프록시 설정, 이미지 width,height 추가
  src/components/chatbot/brand-recommendation-card/BrandRecommendationCard.tsx
  src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
  src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
  src/components/login/login-hello/LoginHello.tsx
  vite.config.ts
Labels: chore 🩹

#194 chore: 프록시 주소 수정
  vite.config.ts
Labels: deploy🚀

#198 deploy: 요청 인터셉터 코드 추가
  src/api/axiosClient.ts
Labels: deploy🚀

#201 chore: 워크플로우 환경변수 추가, 오타 수정
  .github/workflows/node.js.yml
  src/api/axiosClient.ts
  src/api/searchRequests.ts
  src/assets/assets.ts
  src/assets/choose-shoes/again.svg
  src/assets/choose-shoes/camera.svg
  src/assets/choose-shoes/gallery.svg
  src/assets/choose-shoes/rectangle.svg
  src/assets/choose-shoes/search_icon.svg
  src/assets/choose-shoes/shoes_w159.svg
  src/assets/choose-shoes/shoes_w182.svg
  src/assets/mypage/mypage_shoes_room.svg
  src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-search/image-search/againbox/AgainBox.tsx
  src/components/shoes-search/image-search/againbox/againbox.css.ts
  src/components/shoes-search/image-search/analyzeimage/AnalyzeImage.tsx
  src/components/shoes-search/image-search/analyzeimage/analyzeimage.css.ts
  src/components/shoes-search/image-search/analyzeimage/succesproduct/SuccesProduct.tsx
  src/components/shoes-search/image-search/analyzeimage/succesproduct/succesproduct.css.ts
  src/components/shoes-search/image-search/camera-window/CameraWindow.tsx
  src/components/shoes-search/image-search/camera-window/camerawindow.css.ts
  src/components/shoes-search/image-search/gallery/Gallery.tsx
  src/components/shoes-search/isLoading/IsLoading.tsx
  src/components/shoes-search/isLoading/isloading.css.ts
  src/components/shoes-search/itemlistbox/ItemListBox.tsx
  src/components/shoes-search/itemlistbox/itemcard/ItemCard.tsx
  src/components/shoes-search/itemlistbox/itemcard/itemcard.css.ts
  src/components/shoes-search/itemlistbox/itemlistbox.css.ts
  src/components/shoes-search/text-search/mainContainder/MainContainer.tsx
  src/components/shoes-search/text-search/mainContainder/maincontainer.css.ts
  src/components/shoes-search/text-search/mainContainder/textrecordbox/TextRecordBox.tsx
  src/components/shoes-search/text-search/mainContainder/textrecordbox/textrecordbox.css.ts
  src/components/shoes-search/text-search/search-box/SearchBox.tsx
  src/components/shoes-search/text-search/search-box/searchbox.css.ts
  src/components/shoes-search/text-search/textfooter/TextFooter.tsx
  src/components/shoes-search/text-search/textfooter/textfooter.css.ts
  src/hooks/useHandleImageSearchPostHook.ts
  src/hooks/useHandleTextSearchPostHook.ts
  src/hooks/useImageSearchHooks.ts
  src/hooks/useTextSearchHooks.ts
  src/pages/imagesearch-page/ImageSearch.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/textsearch-page/TextSearch.tsx
Labels: chore 🩹

#204 deploy: 워크플로우 env 수정
  .github/workflows/node.js.yml
Labels: deploy🚀

#205 chore:워크플로우 수정
  .github/workflows/node.js.yml
Labels: chore 🩹

#208 refactor-imim
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-info/shoesInfo.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/toastmessage/toastMessage.tsx
  tsconfig.app.tsbuildinfo
Labels: refactor♻️

#213 fix: 채팅 내역 안보이는 버그 수정
  src/components/login/login-hello/LoginHello.tsx
  src/components/sidemenu/SideMenu.tsx
Labels: fix🐛

#216 docs: readme 작성
  README.md
Labels: docs📝
