Repository Perfitt-11-supreme/11-supreme, pull requests merged in 2024-09, with the labels that each got.

#12 style: 텍스트 검색 css 작업 2차 완료
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/contentcontainer/ContentContainer.tsx
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/mainContainder/itemcard/ItemCard.tsx
  src/components/choose-shose/text-search/mainContainder/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
  src/components/choose-shose/text-search/search-box/SearchBox.tsx
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/choose-shose/text-search/textfooter/textfooter.css.ts
  src/components/choose-shose/text-search/textheader/TextHeader.tsx
  src/components/choose-shose/text-search/textheader/search-box/SearchBox.tsx
  src/components/choose-shose/text-search/textheader/search-box/searchbox.css.ts
  src/components/choose-shose/text-search/textheader/textheader.css.ts
Labels: style💄

#26 style:브릿지 페이지 Ui
  src/components/chatbot/brand-plp/BrandPLP.tsx
  src/pages/bridge-page/bridgePage.css.ts
  src/pages/bridge-page/bridgePage.tsx
  src/router/index.tsx
Labels: style💄

#30 Style: ImageSearch 스타일링 1차 작업 완_Jobeomjun
  src/assets/again.svg
  src/assets/analyze.svg
  src/assets/assets.ts
  src/assets/circle.svg
  src/assets/gallery.svg
  src/assets/rectangle.svg
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/image-search/imageSearch.css.ts
  src/components/choose-shose/image-search/imagefooter/ImageFooter.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/AnalyzeItem.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/analyzeitem.css
  src/components/choose-shose/image-search/imagefooter/analyzeitem/analyzeitem.css.ts
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/succesproduct.css.ts
  src/components/choose-shose/image-search/imagefooter/imagefooter.css.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
Labels: style💄

#33 Feat:카메라 촬영 완--Jobemjun
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/cameracomponent/CameraComponent.tsx
  src/components/choose-shose/image-search/camera-window/cameracomponent/cameracomponent.css.ts
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/image-search/imagefooter/ImageFooter.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/AnalyzeItem.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/analyzeitem.css.ts
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/imagefooter/imagefooter.css.ts
Labels: feat✨

#38 Conf:Shoes-TextSearch-Connection---Jobeomjun
  src/components/choose-shose/image-search/camera-window/cameracomponent/CameraComponent.tsx
  src/components/choose-shose/text-search/textheader/TextHeader.tsx
  src/router/index.tsx
Labels: conf💚

#41 chore-SelectItmeCard-border---jobeomjun 선택된 카드 보더
  src/components/choose-shose/image-search/camera-window/cameracomponent/CameraComponent.tsx
  src/components/choose-shose/image-search/camera-window/cameracomponent/cameracomponent.css.ts
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/textheader/TextHeader.tsx
Labels: chore 🩹

#44 Style shoes info
  src/assets/assets.ts
  src/assets/delete.svg
  src/assets/kebab.svg
  src/assets/modify.svg
  src/assets/share.svg
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/choose/Choose.tsx
  src/components/empty-shoes-room/header/Header.tsx
  src/components/empty-shoes-room/shoes-room/ShoesRoom.tsx
  src/components/kebab/Kebab.tsx
  src/components/kebab/kebab.css.ts
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-info/shoes-info.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/star-rating/StarRating.tsx
  src/components/slider/Slider.tsx
  src/router/index.tsx
  src/stores/useRegistryStore.ts
  src/stores/useShoesStore.ts
Labels: style💄

#50 Style: shoesinfo final
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/choose-shose/text-search/textheader/TextHeader.tsx
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/choose/Choose.tsx
  src/components/empty-shoes-room/header/Header.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/slider/Slider.tsx
  src/components/slider/slider.css.ts
  src/stores/useShoesStore.ts
Labels: style💄

#71 feat: firebase
  package-lock.json
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/emptyshoesroom.css.ts
  src/components/empty-shoes-room/header/Header.tsx
  src/components/empty-shoes-room/shoes-room/ShoesRoom.tsx
  src/components/empty-shoes-room/shoes-room/shoesroom.css.ts
  src/components/kebab/Kebab.tsx
  src/components/kebab/kebab.css.ts
  src/components/onboarding/OnBoarding.tsx
  src/components/onboarding/OnBoarding2.tsx
  src/components/onboarding/onboarding.css.ts
  src/components/onboarding/onboarding2.css.ts
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/firebase/firebase.ts
  src/router/index.tsx
  src/stores/useRegistryStore.ts
  src/stores/useShoesStore.ts
  yarn.lock
Labels: style💄, feat✨, refactor♻️, chore 🩹

#73 Feat-imageSearch-API---jobeomjun
  src/api/searchRequests.ts
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/cameraview/CameraView.tsx
  src/components/choose-shose/image-search/cameraview/cameraview.css.ts
  src/components/choose-shose/image-search/imagefooter/ImageFooter.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/AnalyzeItem.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/succesproduct.css.ts
  src/components/choose-shose/image-search/imagefooter/imagefooter.css.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/TextSearch.tsx
  src/stores/useImageSearchStore.ts
  src/stores/useProductStroe.ts
  src/types/data.d.ts
  yarn.lock
Labels: feat✨

#76 fix-변수명오류 교체
  src/components/choose-shose/image-search/imagefooter/analyzeitem/succesproduct/SuccesProduct.tsx
  src/stores/useProductStroe.ts
  yarn.lock
Labels: fix🐛

#82 feat-edit
  package-lock.json
  src/components/empty-shoes-room/choose/choose.css.ts
  src/components/kebab/Kebab.tsx
  src/components/onboarding/OnBoarding.tsx
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/router/index.tsx
  yarn.lock
Labels: feat✨, refactor♻️, chore 🩹

#94 Feat gallery refactor imagesearch jobeomjun
  src/components/choose-shose/gallery/Gallery.tsx
  src/components/choose-shose/gallery/gallery.css.ts
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/image-search/analyzeitem/AnalyzeItem.tsx
  src/components/choose-shose/image-search/analyzeitem/analyzeitem.css.ts
  src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/analyzeitem/succesproduct/succesproduct.css.ts
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/image-search/cameraview/CameraView.tsx
  src/components/choose-shose/image-search/cameraview/cameraview.css.ts
  src/components/choose-shose/image-search/imagefooter/ImageFooter.tsx
  src/components/choose-shose/image-search/imagefooter/imagefooter.css.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/stores/useGalleryStore.ts
  src/stores/useImageSearchStore.ts
Labels: feat✨, refactor♻️

#101 Feat bring itemcard data
  src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/choose/choose.css.ts
  src/components/empty-shoes-room/header/Header.tsx
  src/components/empty-shoes-room/shoes-room/ShoesRoom.tsx
  src/components/empty-shoes-room/shoes-room/shoesroom.css.ts
  src/components/kebab/Kebab.tsx
  src/components/login/Login.tsx
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-info/shoes-info.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/sidemenu/SideMenu.tsx
  src/components/slider/slider.css.ts
  src/components/toastmessage/toast-message.css.ts
  src/components/toastmessage/toastMessage.tsx
  src/pages/chatbot-page/chatBotPage.tsx
  src/types/product.d.ts
Labels: style💄, feat✨, fix🐛

#105 Feat sidemenu api cho hayoon
  src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
  src/components/common/header/Header.tsx
  src/components/empty-shoes-room/user-profile/UserProfile.tsx
  src/components/mypage/size-recommendation-card/SizeRecommendationCard.tsx
  src/components/sidemenu/SideMenu.tsx
  src/components/sidemenu/SidemenuMypageLinks.tsx
  src/pages/chatbot-page/chatBotPage.tsx
  src/pages/liked-page/LikedPage.tsx
  src/pages/mypage/Mypage.tsx
  src/styles/responsive.css.ts
  yarn.lock
Labels: feat✨

#111 Feat user data
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/emptyshoesroom.css.ts
  src/components/empty-shoes-room/user-profile/UserProfile.tsx
  src/pages/mypage/Mypage.tsx
Labels: feat✨, fix🐛

#115 feat-firebaseImageSearch--jobeomjun
  src/components/choose-shose/gallery/Gallery.tsx
  src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/analyzeitem/succesproduct/succesproduct.css.ts
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/imageupload/ImageUpload.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/textupload/TextUpload.ts
  src/firebase/firebase.ts
  src/stores/useGalleryStore.ts
  src/stores/useImageSearchStore.ts
  src/stores/useProductsStore.ts
Labels: feat✨, fix🐛

#121 refactor-imagesearch---jobeomjun
  src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/choose-shose/itemcard/itemcard.css.ts
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/search-box/SearchBox.tsx
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/stores/useImageSearchStore.ts
  src/stores/useSelectItemStore.ts
Labels: fix🐛, refactor♻️

#126 refactor-shosesearch-jobeomjun---이미지 검색 리팩토링3차 완료
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/image-search/analyzeimage/AnalyzeImage.tsx
  src/components/choose-shose/image-search/analyzeimage/analyzeimage.css.ts
  src/components/choose-shose/image-search/analyzeimage/similarproduct/SimilarProduct.tsx
  src/components/choose-shose/image-search/analyzeimage/similarproduct/similarproduct.css.ts
  src/components/choose-shose/image-search/analyzeimage/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/analyzeimage/succesproduct/succesproduct.css.ts
  src/components/choose-shose/image-search/analyzeitem/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/image-search/camera-window/imageupload/ImageUpload.ts
  src/components/choose-shose/image-search/hooks/useHandleImaeSearchPost.ts
  src/components/choose-shose/image-search/hooks/useHandleImageSearchNavigate.ts
  src/stores/useImageSearchStore.ts
Labels: refactor♻️

#135 refactor-textsearch/imagesearch---jobeomjun
  src/components/choose-shose/firebase/imageupload/ImageUpload.ts
  src/components/choose-shose/firebase/textupload/TextUpload.ts
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/hooks/useHandleTextSearchPost.ts
  src/components/choose-shose/text-search/hooks/useTextSearchHooks.ts
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/search-box/SearchBox.tsx
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/onboarding/onboarding.css.ts
  src/stores/useSelectItemStore.ts
  src/stores/useShoesStore.ts
  src/stores/useTextSearchStore.ts
Labels: refactor♻️

#139 Feat-FirebaseTextsearch-jobeomjun
  src/components/choose-shose/firebase/textupload/TextUpload.ts
  src/components/choose-shose/text-search/search-box/SearchBox.tsx
  src/components/onboarding/OnBoarding.tsx
  src/stores/useSelectItemStore.ts
  src/stores/useTextSearchStore.ts
  src/stores/useUserStore.ts
  src/types/user.d.ts
Labels: feat✨

#143 Refactor code refactoring
  src/components/choose-shose/firebase/textupload/TextUpload.ts
  src/components/choose-shose/itemcard/ItemCard.tsx
  src/components/common/button/Button.tsx
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/choose/Choose.tsx
  src/components/onboarding/OnBoarding2.tsx
  src/components/onboarding/onboarding2.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/shoes-registry/star-rating/StarRating.tsx
  src/components/slider/Slider.tsx
  src/types/button.d.ts
  src/types/registry.d.ts
  src/types/shoesroom.d.ts
Labels: style💄, feat✨, fix🐛, refactor♻️, chore 🩹

#147 Refactor Textsearch4 jobeomjun
  src/components/choose-shose/firebase/textupload/FetchTextRecord.ts
  src/components/choose-shose/firebase/textupload/TextUpload.ts
  src/components/choose-shose/image-search/analyzeimage/similarproduct/SimilarProduct.tsx
  src/components/choose-shose/image-search/analyzeimage/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/isLoading/IsLoading.tsx
  src/components/choose-shose/isLoading/isloading.css.ts
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/hooks/useHandleTextSearchPost.ts
  src/components/choose-shose/text-search/hooks/useTextSearchHooks.ts
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/mainContainder/itemlistbox/ItemListBox.tsx
  src/components/choose-shose/text-search/mainContainder/itemlistbox/itemlistbox.css.ts
  src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
  src/components/choose-shose/text-search/mainContainder/textrecordbox/TextRecordBox.tsx
  src/components/choose-shose/text-search/mainContainder/textrecordbox/textrecordbox.css.ts
  src/components/choose-shose/text-search/search-box/SearchBox.tsx
  src/components/choose-shose/text-search/textfooter/TextFooter.tsx
  src/components/choose-shose/text-search/textfooter/textfooter.css.ts
  src/components/onboarding/OnBoarding.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/stores/useTextSearchStore.ts
  src/styles/responsive.css.ts
Labels: refactor♻️

#153 Refactor-Responsiv---jobeomjun-아울렛 설정
  src/App.tsx
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/mainContainder/MainContainer.tsx
  src/components/choose-shose/text-search/mainContainder/maincontainer.css.ts
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/foot-info/FootInfo.tsx
  src/components/login/LoginHello.tsx
  src/components/onboarding/OnBoarding.tsx
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/pages/bridge-page/bridgePage.tsx
  src/pages/chatbot-page/chatBotPage.tsx
  src/pages/liked-page/LikedPage.tsx
  src/pages/not-found/notFound.tsx
  src/pages/share-page/SharePage.tsx
  src/pages/viewed-history-page/ViewedHistoryPage.tsx
  src/router/index.tsx
Labels: refactor♻️

#154 refactor-imagesearch4-jobeomjun--이미지검색 리팩토링4차 완료
  src/components/choose-shose/firebase/imageupload/ImageUpload.ts
  src/components/choose-shose/image-search/ImageSearch.tsx
  src/components/choose-shose/image-search/analyzeimage/AnalyzeImage.tsx
  src/components/choose-shose/image-search/analyzeimage/similarproduct/SimilarProduct.tsx
  src/components/choose-shose/image-search/analyzeimage/succesproduct/SuccesProduct.tsx
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/hooks/useHandleImageSearchNavigate.ts
  src/components/choose-shose/image-search/hooks/useImaeSearchPost.ts
  src/components/choose-shose/image-search/hooks/useImageSearchHooks.ts
  src/components/choose-shose/text-search/TextSearch.tsx
  src/components/choose-shose/text-search/mainContainder/itemlistbox/ItemListBox.tsx
  src/stores/useImageSearchStore.ts
  src/stores/useTextSearchStore.ts
Labels: refactor♻️

#156 Refactor:채팅 컴포넌트 함수 분리
  src/components/chatbot/product-filter/ProductFilter.tsx
  src/components/chatbot/product-recommendation-preview/ProductRecommendationPreview.tsx
  src/components/chatbot/product-recommendation/ProductRecommendation.tsx
  src/components/common/chatbot-search-input/ChatbotSearchInput.tsx
  src/components/common/common-guide/CommonGuide.tsx
  src/components/common/product-recommendation-card/ProductRecommendationCard.tsx
  src/components/login/LoginHello.tsx
  src/components/login/loginchatbot/recommendbox/RecommendBox.tsx
  src/components/sidemenu/SideMenu.tsx
  src/components/sidemenu/SidemenuList.tsx
  src/hooks/useAuthHook.ts
  src/hooks/useChatCompletionHook.ts
  src/hooks/useChatHistoryHook.ts
  src/hooks/useFetchChatHistoryHook.ts
  src/router/index.tsx
  src/stores/useUIStateStore.ts
  src/utils/bridgePageUtils.ts
Labels: fix🐛, refactor♻️

#158 Conf:build test
  src/components/choose-shose/image-search/analyzeimage/similarproduct/similarproduct.css.ts
  src/components/common/header/Header.tsx
  src/components/deleteuser/DeleteUserModal.tsx
  src/components/foot-info/foot-info.css.ts
  src/components/foot-info/my-foot-info.css.ts
  src/components/kebab/Kebab.tsx
  src/components/login/Login.tsx
  src/components/login/LoginHello.tsx
  src/components/login/login.css.ts
  src/components/login/loginchatbot/recommendbox/RecommendBox.tsx
  src/components/onboarding/onboarding.css.ts
  src/components/shoes-info/ShoesInfo.tsx
  src/components/shoes-info/shoes-info.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/sidemenu/SideMenu.tsx
  src/components/signup/signup.css.ts
  src/hooks/useChatCompletionHook.ts
  src/index.css.ts
  src/pages/bridge-page/bridgePage.css.ts
  src/pages/chatbot-page/chatBotPage.css.ts
  src/pages/loading-page/loadingPage.css.ts
  src/pages/mypage/Mypage.tsx
  src/pages/not-found/notFound.css.ts
  src/styles/responsive.css.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
  vercel.json
Labels: style💄, conf💚

#165 fix-loading
  src/components/empty-shoes-room/EmptyShoesRoom.tsx
  src/components/empty-shoes-room/choose/Choose.tsx
  src/components/empty-shoes-room/choose/choose.css.ts
  src/components/empty-shoes-room/header/Header.tsx
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/shoes-registry/star-rating/StarRating.tsx
  src/components/slider/Slider.tsx
  src/stores/useRegistryStore.ts
Labels: style💄, feat✨, fix🐛

#168 feat: userImage
  src/App.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/button.css.ts
  src/components/empty-shoes-room/emptyshoesroom.css.ts
  src/components/empty-shoes-room/user-profile/UserProfile.tsx
  src/components/empty-shoes-room/user-profile/userprofile.css.ts
  src/components/shoes-info/shoes-info.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/sidemenu/SidemenuMypageLinks.tsx
  src/components/sidemenu/sidemenuMypageLinks.css.ts
  src/index.css.ts
  src/pages/mypage/Mypage.tsx
  src/styles/responsive.css.ts
  src/types/button.d.ts
Labels: style💄, feat✨

#169 Fix commonstylefix jobeomjun
  src/components/choose-shose/image-search/analyzeimage/analyzeimage.css.ts
  src/components/choose-shose/image-search/camera-window/CameraWindow.tsx
  src/components/choose-shose/image-search/camera-window/camerawindow.css.ts
  src/components/choose-shose/text-search/search-box/searchbox.css.ts
  src/components/choose-shose/text-search/textfooter/textfooter.css.ts
  src/components/common/button/button.css.ts
  src/components/common/header/header.css.ts
  src/components/deleteuser/DeleteUserModal.tsx
  src/components/login/login-hello/loginHello.css.ts
  src/components/login/login.css.ts
  src/components/shoes-registry/ShoesRegistry.tsx
  src/components/shoes-registry/shoesregistry.css.ts
  src/components/signup/signup.css.ts
  src/components/toastmessage/toast-message.css.ts
  src/styles/media.css.ts
  src/styles/responsive.css.ts
Labels: style💄, fix🐛
